# Generated by Django 4.1.3 on 2022-11-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(max_length=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.TextField(max_length=64),
        ),
    ]
